import { getProviders, getSession, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import BolaoPage from "../components/BolaoPage";
import Login from "../components/Login/index";
import styles from "../styles/Home.module.css";

export default function Home({ providers }) {
  const { data: session } = useSession();
  const user = session?.user;

  if (!session) return <Login providers={providers} />;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button
          onClick={(e) => {
            e.preventDefault();
            signOut();
          }}
        >
          Logout
        </button>
        
        <BolaoPage />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      providers,
      session,
    },
  };
}